/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazadaptable;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ACER
 */
public class Inicio extends javax.swing.JFrame {
    int xMause, yMause;
    boolean FlagUsuario,FlagContraseña;
    private static boolean FlagRecordar;
    InterfazAdaptable interfaz= new InterfazAdaptable();
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        panel.setVisible(false);
        contraseña.requestFocusInWindow();
        this.setShape(new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 50, 40));
        try {
            UIManager.put( "Button.arc", 100 );
            UIManager.put( "TextComponent.arc",100);
            UIManager.setLookAndFeel(new FlatLightLaf());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        Error1.setVisible(false);
        Error2.setVisible(false);
        String [] recordar=Data.LeerRecuerdo();
        if(!recordar[0].equals("")){
         usuario.setText(recordar[0]);
         contraseña.setText(recordar[1]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        bar = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        Recordar = new javax.swing.JRadioButton();
        Iniciar = new javax.swing.JButton();
        registrarse = new javax.swing.JLabel();
        cambiarContraseña = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        Barra = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        Error1 = new javax.swing.JLabel();
        Error2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cargando...");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 300, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 22)); // NOI18N
        jLabel2.setText("Correo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 150, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 40)); // NOI18N
        jLabel3.setText("Inicio de sesion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Reparaciones y demas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 240, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Untitled_logo_1_free-file.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 270, 170));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 30, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 22)); // NOI18N
        jLabel6.setText("Contraseña:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bloquear (1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 30, 30));

        contraseña.setToolTipText("Ingresa tu contraseña");
        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 260, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Bienvenido de nuevo!");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 230, 40));

        Recordar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Recordar.setText("Recordar");
        Recordar.setToolTipText("Recordar correo y contraseña al salir");
        Recordar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordarActionPerformed(evt);
            }
        });
        getContentPane().add(Recordar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        Iniciar.setBackground(new java.awt.Color(0, 0, 0));
        Iniciar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Iniciar.setForeground(new java.awt.Color(255, 255, 102));
        Iniciar.setText("Iniciar sesion");
        Iniciar.setToolTipText("Click para iniciar sesion");
        Iniciar.setBorder(null);
        Iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IniciarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IniciarMousePressed(evt);
            }
        });
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });
        getContentPane().add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 210, 40));

        registrarse.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        registrarse.setForeground(new java.awt.Color(51, 51, 51));
        registrarse.setText("aqui");
        registrarse.setToolTipText("Click para crear una cuenta nueva");
        registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registrarseMousePressed(evt);
            }
        });
        getContentPane().add(registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 410, 50, 20));

        cambiarContraseña.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        cambiarContraseña.setText("Olvide mi contraseña.");
        cambiarContraseña.setToolTipText("Click aqui para cambiar tu contraseña");
        cambiarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cambiarContraseñaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cambiarContraseñaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cambiarContraseñaMousePressed(evt);
            }
        });
        getContentPane().add(cambiarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 160, 20));
        cambiarContraseña.getAccessibleContext().setAccessibleDescription("");

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        jLabel11.setText("Registrate");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 70, 20));

        usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuario.setToolTipText("Ingresa tu correo electronico, con el que creaste tu cuenta");
        usuario.setBorder(null);
        usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioMousePressed(evt);
            }
        });
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 260, 30));

        Barra.setBackground(new java.awt.Color(204, 204, 204));
        Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMouseDragged(evt);
            }
        });
        Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMousePressed(evt);
            }
        });

        cerrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("X");
        cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrar.setOpaque(true);
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BarraLayout = new javax.swing.GroupLayout(Barra);
        Barra.setLayout(BarraLayout);
        BarraLayout.setHorizontalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(630, Short.MAX_VALUE))
        );
        BarraLayout.setVerticalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        getContentPane().add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        Error1.setForeground(new java.awt.Color(204, 0, 204));
        Error1.setText("*No se ha escrito");
        getContentPane().add(Error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        Error2.setForeground(new java.awt.Color(204, 0, 204));
        Error2.setText("*No se ha escrito");
        getContentPane().add(Error2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 660, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RecordarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecordarActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IniciarActionPerformed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        cerrar.setBackground(new Color(200, 57, 43));
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        cerrar.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_cerrarMouseExited

    private void BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xMause, y-yMause);
    }//GEN-LAST:event_BarraMouseDragged

    private void BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMousePressed
        xMause =evt.getX();
        yMause= evt.getY();
    }//GEN-LAST:event_BarraMousePressed

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaActionPerformed

    private void usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMouseClicked

    }//GEN-LAST:event_usuarioMouseClicked

    private void usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMousePressed
        
    }//GEN-LAST:event_usuarioMousePressed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void registrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseMouseEntered
        registrarse.setForeground(Color.gray);
    }//GEN-LAST:event_registrarseMouseEntered

    private void registrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseMouseExited
        registrarse.setForeground(Color.black);
    }//GEN-LAST:event_registrarseMouseExited

    private void cambiarContraseñaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarContraseñaMouseEntered
        cambiarContraseña.setForeground(Color.gray);
    }//GEN-LAST:event_cambiarContraseñaMouseEntered

    private void cambiarContraseñaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarContraseñaMouseExited
        cambiarContraseña.setForeground(Color.black);
    }//GEN-LAST:event_cambiarContraseñaMouseExited

    private void registrarseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseMousePressed
        Registro registro=new Registro();
        registro.setVisible(true);
        ((JFrame) SwingUtilities.getWindowAncestor(registrarse)).dispose();
    }//GEN-LAST:event_registrarseMousePressed

    private void IniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarMouseEntered
       Iniciar.setForeground(Color.gray);
    }//GEN-LAST:event_IniciarMouseEntered

    private void IniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarMouseExited
        Iniciar.setForeground(Color.yellow);
    }//GEN-LAST:event_IniciarMouseExited

    private void cambiarContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarContraseñaMousePressed
        OlvideMiContraseña obj=new OlvideMiContraseña();
        obj.setVisible(true);
        ((JFrame) SwingUtilities.getWindowAncestor(cambiarContraseña)).dispose();
    }//GEN-LAST:event_cambiarContraseñaMousePressed

    private void IniciarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarMousePressed
        Error1.setVisible(false);
        Error2.setVisible(false);
        FlagUsuario= !usuario.getText().isEmpty();
        FlagContraseña=!contraseña.getText().isEmpty();
        Iniciar.add(Recordar);
                if (Recordar.isSelected()) {
                    FlagRecordar = true;
                } else {
                    FlagRecordar = false;
                }

        if(!(FlagUsuario&&FlagContraseña)){
            if(!FlagUsuario&&!FlagContraseña){
            JOptionPane.showMessageDialog(null, "No se ha escrito usario y contraseña");
            Error1.setVisible(true);
            Error2.setVisible(true);
           }else{
         if(!(FlagContraseña)){
            JOptionPane.showMessageDialog(null, "No se ha escrito la contraseña");
            Error2.setVisible(true);
            }
         if(!(FlagUsuario)){
                JOptionPane.showMessageDialog(null, "No se ha escrito el usario");
                Error1.setVisible(true);
            }
           }
        }else{
            char[] password = contraseña.getPassword();
            String contraseña=String.valueOf(password);
            //Compara en la base de datos(en este caso local, pero adaptable), si existe el perfil(correo y contraseña)
            if(Data.Comparador(usuario.getText(), contraseña)){
                if(FlagRecordar){
                    //Guardar Datos para recordar el proximo inicio de sesion.
                Data.GuardarRecuerdo(usuario.getText(),contraseña);
                }else{
                Data.GuardarRecuerdo("", "");
                }
                //barra de carga
                Thread hilo= new Thread(){
                @Override
                        public void run(){
                panel.setVisible(true);
                for(int i=1;i<101;i++){
                    try {
                    Thread.sleep( 10);
                    bar.setValue(i);
                    } catch (InterruptedException e) {
                    }
                }
            Bienvenida bienvenida=new Bienvenida();
            bienvenida.setVisible(true);
            ((JFrame) SwingUtilities.getWindowAncestor(Iniciar)).dispose();
                        }
                        };
                hilo.start();
        }else{
            JOptionPane.showMessageDialog(null, "contraseña o usuario incorrecto*");
            }
        }
    }//GEN-LAST:event_IniciarMousePressed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JLabel Error1;
    private javax.swing.JLabel Error2;
    private javax.swing.JButton Iniciar;
    private javax.swing.JRadioButton Recordar;
    private javax.swing.JProgressBar bar;
    private javax.swing.JLabel cambiarContraseña;
    private javax.swing.JLabel cerrar;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel registrarse;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
