/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazadaptable;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author Juan Haydar
 */
public class Registro extends javax.swing.JFrame {
    int xMause, yMause;
    boolean FlagCorreo,FlagContraseña,FlagContraseña2;
    InterfazAdaptable interfaz= new InterfazAdaptable();
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        panel.setVisible(false);
        contraseña.requestFocusInWindow();
        this.setShape(new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 50, 40));
        try {
            UIManager.put( "Button.arc", 100 );
            UIManager.put( "TextComponent.arc",100);
            UIManager.setLookAndFeel(new FlatLightLaf());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        Error1.setVisible(false);
        Error2.setVisible(false);
        Error3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        bar = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        Registrar = new javax.swing.JButton();
        cambiarContraseña = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        Barra = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        contraseña2 = new javax.swing.JPasswordField();
        jRadioButton2 = new javax.swing.JRadioButton();
        Volver = new javax.swing.JLabel();
        Error1 = new javax.swing.JLabel();
        Error2 = new javax.swing.JLabel();
        Error3 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cargando...");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 300, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 22)); // NOI18N
        jLabel2.setText("Correo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 150, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 40)); // NOI18N
        jLabel3.setText("Registro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 30, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 22)); // NOI18N
        jLabel6.setText("Contraseña:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 150, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bloquear (1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 30, 30));

        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 280, 30));

        Registrar.setBackground(new java.awt.Color(0, 0, 0));
        Registrar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Registrar.setForeground(new java.awt.Color(255, 255, 102));
        Registrar.setText("Registrarme");
        Registrar.setToolTipText("Guardar informacion");
        Registrar.setBorder(null);
        Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrarMousePressed(evt);
            }
        });
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 210, 40));

        cambiarContraseña.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cambiarContraseña.setText("Ya tienes cuenta? ");
        getContentPane().add(cambiarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, 30));

        correo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        correo.setForeground(new java.awt.Color(204, 204, 204));
        correo.setText("Ingresar correo electronico");
        correo.setBorder(null);
        correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                correoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                correoMousePressed(evt);
            }
        });
        correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoActionPerformed(evt);
            }
        });
        getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 270, 30));

        Barra.setBackground(new java.awt.Color(204, 204, 204));
        Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMouseDragged(evt);
            }
        });
        Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMousePressed(evt);
            }
        });

        cerrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("X");
        cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrar.setOpaque(true);
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BarraLayout = new javax.swing.GroupLayout(Barra);
        Barra.setLayout(BarraLayout);
        BarraLayout.setHorizontalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(380, Short.MAX_VALUE))
        );
        BarraLayout.setVerticalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        getContentPane().add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("<html><body style='width: 300px'>Crea tu nueva cuenta para guardar  tu informacion</body></html>");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 330, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 0, 22)); // NOI18N
        jLabel10.setText("Repite tu contraseña:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 210, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bloquear (1).png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 30, 30));

        contraseña2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseña2ActionPerformed(evt);
            }
        });
        getContentPane().add(contraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 280, 30));

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("<html><body style='width: 230px'>Acepto los Términos de Servicios y  Política de privacidad.</body></html>");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 350, -1));

        Volver.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Volver.setText("Iniciar sesion.");
        Volver.setToolTipText("Click para devolverte a la pagina de inicio");
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VolverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VolverMousePressed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 90, 30));

        Error1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Error1.setForeground(new java.awt.Color(204, 0, 204));
        Error1.setText("*No se ha escrito");
        getContentPane().add(Error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        Error2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Error2.setForeground(new java.awt.Color(204, 0, 204));
        Error2.setText("*No se ha escrito");
        getContentPane().add(Error2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        Error3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Error3.setForeground(new java.awt.Color(204, 0, 204));
        Error3.setText("*No se ha escrito");
        getContentPane().add(Error3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoVertical.png"))); // NOI18N
        fondo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 410, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarActionPerformed

    private void correoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoMouseClicked

    }//GEN-LAST:event_correoMouseClicked

    private void correoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoMousePressed
        String txt="Ingresar correo electronico";
        interfaz.Texto(correo, txt);
    }//GEN-LAST:event_correoMousePressed

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoActionPerformed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        cerrar.setBackground(new Color(200, 57, 43));
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        cerrar.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_cerrarMouseExited

    private void BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xMause, y-yMause);
    }//GEN-LAST:event_BarraMouseDragged

    private void BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMousePressed
        xMause =evt.getX();
        yMause= evt.getY();
    }//GEN-LAST:event_BarraMousePressed

    private void contraseña2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseña2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseña2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void VolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseEntered
       Volver.setForeground(Color.gray);
    }//GEN-LAST:event_VolverMouseEntered

    private void VolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseExited
        Volver.setForeground(Color.black);
    }//GEN-LAST:event_VolverMouseExited

    private void VolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMousePressed
        Inicio inicio=new Inicio();
        inicio.setVisible(true);
        ((JFrame) SwingUtilities.getWindowAncestor(Volver)).dispose();
    }//GEN-LAST:event_VolverMousePressed
private String getPassword(JPasswordField Jpassword){
    char[] password = Jpassword.getPassword();
    String contraseña=String.valueOf(password);
    return contraseña;
    }
    private void RegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMousePressed
    FlagCorreo= interfaz.bandera(correo, "Ingresar correo electronico");
    FlagContraseña=!contraseña.getText().isEmpty();
    FlagContraseña2=!contraseña2.getText().isEmpty();
    if(!(getPassword(contraseña).equals(getPassword(contraseña2)))){
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
        }else if(FlagCorreo&&(!correo.getText().contains("@")||correo.getText().length()<9||correo.getText().length()>45)){
                FlagCorreo=false;
                JOptionPane.showMessageDialog(null,"Correo no valido");
                interfaz.Texto(correo, "Example@gmail.com");
        }else{
            Error1.setVisible(!FlagCorreo);
            Error2.setVisible(!FlagContraseña);
            Error3.setVisible(!FlagContraseña2);
            
            if(Data.Comparador2(correo.getText())){
            JOptionPane.showMessageDialog(null, "Ya se creo una cuenta, con este correo.");
            }else {
                if(FlagContraseña&&FlagContraseña2&&FlagCorreo){
                /**Agrega aqui tu funcion para guardar valores en la base de datos
                *(En este caso local, pero reemplazalo por la tuya)**/
                Data.setContraseña(getPassword(contraseña));
                Data.setCorreo(correo.getText());
                Data.Guardado();
                //barra de carga
                Thread hilo= new Thread(){
                @Override
                        public void run(){
                panel.setVisible(true);
                for(int i=1;i<101;i++){
                    try {
                    Thread.sleep( 7);
                    bar.setValue(i);
                    } catch (InterruptedException e) {
                    }
                }
                JOptionPane.showMessageDialog(null, "Datos Guardados");
           
                //mostrar siguiente panel
                Inicio inicio=new Inicio();
                inicio.setVisible(true);
                ((JFrame) SwingUtilities.getWindowAncestor(Registrar)).dispose();
                        }
                        };
                hilo.start();
                }else{
            Error1.setVisible(!FlagCorreo);
            Error2.setVisible(!FlagContraseña);
            Error3.setVisible(!FlagContraseña2);
            } } 
        }
    }//GEN-LAST:event_RegistrarMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JLabel Error1;
    private javax.swing.JLabel Error2;
    private javax.swing.JLabel Error3;
    private javax.swing.JButton Registrar;
    private javax.swing.JLabel Volver;
    private javax.swing.JProgressBar bar;
    private javax.swing.JLabel cambiarContraseña;
    private javax.swing.JLabel cerrar;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JPasswordField contraseña2;
    private javax.swing.JTextField correo;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
